Don't move from an rvalue: it prevents copy-elision
This fixes these Clang 3.8 warnings:
    src/fpath.cpp:401:20: error: moving a temporary object prevents
        copy elision [-Werror,-Wpessimizing-move]
            pathResults[id] = std::move(task.get_future());
                              ^
    src/fpath.cpp:401:20: note: remove std::move call here
            pathResults[id] = std::move(task.get_future());
                              ^~~~~~~~~~                 ~

    lib/qtgame/wzapp_qt.cpp:134:11: error: moving a local object in a
        return statement prevents copy elision [-Werror,-Wpessimizing-move]
                   return std::move(image);
                          ^
    lib/qtgame/wzapp_qt.cpp:134:11: note: remove std::move call here
                            return std::move(image);
                                   ^~~~~~~~~~     ~