Fix clang error
Fixes the following error from clang:

netplay.cpp:1786:2: error: multiple conversions from switch condition type 'std::atomic_int' (aka 'atomic<int>') to an integral or enumeration type
        switch (upnp_status)
        ^       ~~~~~~~~~~~
/usr/include/c++/v1/atomic:860:5: note: conversion to integral type 'int'
    operator _Tp() const volatile _NOEXCEPT {return load();}
    ^
/usr/include/c++/v1/atomic:862:5: note: conversion to integral type 'int'
    operator _Tp() const _NOEXCEPT          {return load();}
    ^

Since upnp_status is atomic and it's checked multiple times in this funcition, it seems more correct to store value of upnp_status into a local variable and check in in both switch and if's.