Fix compile error, make <GL/glew.h> be included before <GL/gl.h>.
/usr/include/GL/glew.h:84:2: error: #error gl.h included before glew.h
/usr/include/GL/glew.h:87:2: error: #error glext.h included before glew.h

Introduced in 8d5b07485f1b8e4e118b9f6a07bf837e9f85bce4, but was probably just waiting to happen.